name: Stations Weekly

on:
  schedule:
    - cron: '59 21 * * 5'  # ~23:59 Europe/Paris en été (UTC+2)
    - cron: '59 22 * * 5'  # ~23:59 Europe/Paris en hiver (UTC+1)
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  fetch-stations:
    runs-on: ubuntu-latest
    # Variables d'env pour tout le job
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      MF_BASIC_AUTH_B64: ${{ secrets.MF_BASIC_AUTH_B64 }} # base64(id:secret)
      METEO_TOKEN_CACHE: ${{ runner.temp }}/mf_token.json
      ALT_SELECT: '1000' # selection de l'altitude minimale des stations
    steps:
      - uses: actions/checkout@v4

      # Ne bloque que les exécutions CRON, pas les run manuels
      - name: Gate by local time Europe/Paris
        if: ${{ github.event_name == 'schedule' }}
        run: .github/scripts/should_run.sh fri-23:59

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps with uv
        run: |
          uv pip install requests python-dateutil boto3 --system

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch stations → DynamoDB (pipe)
        run: |
          python -m src.download.fetch_stations \
            --scales "quotidienne" \ 
            --departments "38,73,74" \
          | python -m src.upload.stdin_to_dynamodb --table Stations --pk id
      
      # autre scales ",horaire,infrahoraire-6m"
